### ISSUE TITLE
[BUG] output transformers strips out fields with anyOf schema

### ISSUE THREAD

**Issue by Celleb** [acrontum/generate-it#104]
**Describe the bug**
Properties with anyOf schema are striped out from output transformers.

Given the following schemas:
`user/model.yml`
```yaml
anyOf:
  - $ref: ./driver/model.yml
  - $ref: ./passenger/model.yml
discriminator:
  propertyName: type
```
```yaml
type: object
properties:
  token:
    type: string
    readOnly: true
    example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5Y3BCVzRKSU0zYWVE...
  user:
    $ref: user/model.yml
required:
  - user
  - token
```
Produces

```ts
export default {
  // authorize
  authorize: {
    token: String
  }
}
```

**To Reproduce**
1. Generate the backend from the swagger file
2. Inspect the generated output transformer

**Expected behavior**
The transformer has the correct fields and types or at least allows any field to pass.

**Node & NPM version**
Node: 12.18.2
NPM: 6.14.8

**Operating system:**
 - OS: MacOS
 - Version: 11.2.2

**Additional context**
Using OAS3
