### ISSUE TITLE
[BUG] Empty array inputs are not respected by the validator.

### ISSUE THREAD

**Issue by jonmanga** [acrontum/generate-it#29]
**Describe the bug**
Given an input definition that has an item of type array that's marked required, the validator fails the input when given an empty array. Even when the `minItems` is set to 0. Empty arrays should be valid inputs unless specified otherwise.

**To Reproduce**
1. Define an input object with one more property as required arrays.
For example
```yaml
type: object
required:
- items
properties:
  items:
    type: array
    items:
      type: string
```

**Expected behavior**
An empty array should pass the validation
For example, given the following input:
```json
{
    "items":[]
}
```
Should pass the validation.
