### ISSUE TITLE
[BUG] JwtAccess type is assumed but need to exist

### ISSUE THREAD

**Issue by atillabaspinar-acrontum** [acrontum/generate-it#74]
**Describe the bug**
JwtAccess type is assumed to be defined. If not, the app cannot be built. The type is actually generated if there is a definition for it in the yml file. 

**To Reproduce**
Run generate-it against a yml file which does not contain JwtAccess. eg:
```
 JwtAccess:
      type: object
      required:
        - id
      properties:
        id:
          type: number
```

**Expected behavior**
If there is no use of JWT Token, then generated files should not refer to it.

**Node & NPM version**
Node: 12.16.1
Npm 6.14.8

**Operating system:**
 - OS: Ubuntu
 - Version 18.4
